"use client";
import { useMemo, useState } from "react";
const questions=[
 {subject:"বাংলা",chapter:"ধ্বনি ও বর্ণ",level:1,q:"বাংলা ভাষায় কোন স্বরধ্বনি উচ্চারণকালে জিহ্বা উচ্চ অবস্থানে থাকে?",options:["আ","এ","ও","উ"],correct:3,solution:"‘উ’ একটি উচ্চ স্বরধ্বনি। এটি উচ্চারণের সময় জিহ্বা মুখগহ্বরের উচ্চ অবস্থানে থাকে।"},
 {subject:"বাংলা",chapter:"শব্দের উৎস",level:1,q:"বাংলা শব্দভাণ্ডারে অনার্য জাতির ব্যবহৃত শব্দ কোন শ্রেণির?",options:["তৎসম","তদ্ভব","বিদেশি","দেশি"],correct:3,solution:"বাংলায় বসবাসকারী অনার্য জনগোষ্ঠীর ভাষা থেকে আগত শব্দকে দেশি শব্দ বলা হয়।"},
 {subject:"বাংলা",chapter:"ভাষাবিজ্ঞান",level:2,q:"‘ধ্বনিবিজ্ঞান ও বাংলা ধ্বনিতত্ত্ব’ গ্রন্থের রচয়িতা কে?",options:["মুহম্মদ শহীদুল্লাহ্","মুনীর চৌধুরী","মুহম্মদ এনামুল হক","মুহম্মদ আবদুল হাই"],correct:3,solution:"গ্রন্থটির রচয়িতা ভাষাবিজ্ঞানী ড. মুহম্মদ আবদুল হাই।"},
 {subject:"বাংলা",chapter:"বর্ণমালা",level:2,q:"বাংলা বর্ণমালায় যৌগিক স্বরবর্ণ কয়টি?",options:["১টি","৩টি","৪টি","২টি"],correct:3,solution:"বাংলা বর্ণমালায় যৌগিক স্বরবর্ণ ২টি—ঐ (এ+ই) এবং ঔ (অ+উ)।"},
 {subject:"বাংলা",chapter:"শব্দতত্ত্ব",level:3,q:"যোগরূঢ় শব্দ কোনটি?",options:["কলম","মলম","বাঁশি","শাখামৃগ"],correct:3,solution:"শাখামৃগ শব্দটির ব্যুৎপত্তিগত অর্থ আলাদা হলেও প্রচলিত বিশেষ অর্থ ‘বানর’; তাই এটি যোগরূঢ় শব্দ।"},
 {subject:"বাংলা",chapter:"উপসর্গ",level:3,q:"উপসর্গযুক্ত শব্দ কোনটি?",options:["বিদ্যা","বিষয়","বিপুল","বিদ্রোহী"],correct:3,solution:"বিদ্রোহী = বি (উপসর্গ) + দ্রোহী। এখানে ‘বি’ উপসর্গটি বিরুদ্ধতার অর্থ প্রকাশ করে।"}
];
const subjects=[["বাংলা",72],["ইংরেজি",48],["গণিত",31],["বাংলাদেশ বিষয়াবলি",64],["সাধারণ বিজ্ঞান",81],["আন্তর্জাতিক বিষয়াবলি",41]];
const chapters=["ধ্বনি ও বর্ণ","শব্দের উৎস","ভাষাবিজ্ঞান","বর্ণমালা","শব্দতত্ত্ব","উপসর্গ"];
export default function AdaptivePractice({onComplete}:{onComplete:()=>void}){
 const [level,setLevel]=useState(1),[index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[answered,setAnswered]=useState(false),[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0),[chapter,setChapter]=useState("ধ্বনি ও বর্ণ");
 const pool=useMemo(()=>questions.filter(x=>x.level<=Math.min(3,level+1)),[level]); const item=pool[index%pool.length]; const rating=Math.round(42+correct*9+Math.max(0,level-1)*4); const passGap=Math.max(0,60-rating);
 const choose=(i:number)=>{if(answered)return;setSelected(i);setAnswered(true);setAttempts(v=>v+1);if(i===item.correct){setCorrect(v=>v+1);setLevel(v=>Math.min(3,v+1))}else setLevel(v=>Math.max(1,v-1))};
 const next=()=>{setAnswered(false);setSelected(null);setIndex(v=>v+1);setChapter(pool[(index+1)%pool.length]?.chapter||"ধ্বনি ও বর্ণ")};
 return <section className="adaptive"><header className="adaptive-head"><div><span>46th BCS প্রশ্নভিত্তিক অভিযোজিত অনুশীলন</span><h1>আপনার প্রস্তুতি, আপনার গতিতে</h1><p>সঠিক উত্তরে কঠিন প্রশ্ন, ভুল উত্তরে সহজ ব্যাখ্যা ও ভিত্তি পুনর্গঠন।</p></div><div className="adaptive-rating"><small>বর্তমান রেটিং</small><b>{rating}</b><span>পাসিং গ্রেড থেকে {passGap} পয়েন্ট দূরে</span></div></header>
 <div className="adaptive-layout"><aside className="adaptive-side"><small>UP NEXT</small><h2>{chapter}</h2><p>বর্তমান কঠিনতা: <b>লেভেল {level}</b></p><button onClick={()=>document.getElementById("adaptive-question")?.scrollIntoView({behavior:"smooth"})}>আমার পথ শুরু করুন</button><div><small>পূর্বের অধ্যায়</small>{chapters.map((x,i)=><button className={chapter===x?"active":""} onClick={()=>{setChapter(x);setIndex(i);setAnswered(false);setSelected(null)}} key={x}><i>{i<Math.min(attempts,chapters.length)?"✓":"○"}</i>{x}</button>)}</div></aside>
 <main className="adaptive-main"><section className="mastery-map"><div className="mastery-wheel"><div><b>{rating}</b><small>সামগ্রিক দক্ষতা</small></div></div><div className="mastery-list"><header><div><small>বিষয়ভিত্তিক নলেজ ম্যাপ</small><h2>কোথায় শক্তিশালী, কোথায় ঘাটতি</h2></div><span>{correct}/{attempts} সঠিক</span></header>{subjects.map((x,i)=><button key={x[0]} onClick={()=>i===0&&setChapter("ধ্বনি ও বর্ণ")}><i className={Number(x[1])>=70?"strong":Number(x[1])>=50?"developing":"focus"}/><span><b>{x[0]}</b><small>{x[1]}% দক্ষতা</small></span><em style={{"--mastery":x[1]+"%"} as React.CSSProperties}/></button>)}</div></section>
 <section className="adaptive-path"><header><div><small>AI RECOMMENDED PATH</small><h2>পরবর্তী শেখার সংক্ষিপ্ত পথ</h2></div><span>পারফরম্যান্স অনুযায়ী স্বয়ংক্রিয়ভাবে বদলাবে</span></header><div>{[["১","ধারণা শিখুন",chapter],["২","সহজ অনুশীলন","৫টি প্রশ্ন"],["৩","অভিযোজিত MCQ","বর্তমান লেভেল "+level],["৪","মিনি মূল্যায়ন","দক্ষতা যাচাই"]].map((x,i)=><article className={i===Math.min(3,answered?2:0)?"current":""} key={x[0]}><i>{x[0]}</i><small>{x[1]}</small><b>{x[2]}</b></article>)}</div></section>
 <section className="adaptive-question" id="adaptive-question"><header><div><small>{item.subject} · {item.chapter}</small><b>46th BCS প্রশ্ন · অভিযোজিত লেভেল {level}</b></div><span>প্রশ্ন {attempts+1}</span></header><h2>{item.q}</h2><div className="adaptive-options">{item.options.map((x,i)=><button disabled={answered} onClick={()=>choose(i)} className={answered?(i===item.correct?"correct":selected===i?"wrong":""):""} key={x}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}</div>{answered&&<div className={selected===item.correct?"adaptive-solution success":"adaptive-solution"}><b>{selected===item.correct?"✓ সঠিক উত্তর—কঠিনতা এক ধাপ বাড়ল":"✕ উত্তরটি সঠিক নয়—পরের প্রশ্ন সহজ হবে"}</b><p><strong>সমাধান:</strong> {item.solution}</p><div><button onClick={()=>setChapter(item.chapter)}>আগের অধ্যায়টি আবার শিখুন</button><button onClick={next}>পরবর্তী অভিযোজিত প্রশ্ন →</button></div></div>}</section>
 <section className="adaptive-plan"><div><small>পাসিং গ্রেডে পৌঁছানোর ব্যক্তিগত পরিকল্পনা</small><h2>{passGap?"আরও "+passGap+" পয়েন্ট উন্নতি প্রয়োজন":"আপনি বর্তমান পাসিং লক্ষ্যে পৌঁছেছেন"}</h2><p>আপনার ভুল, সময় ও বিষয়ভিত্তিক দক্ষতার ভিত্তিতে পরিকল্পনাটি তৈরি হয়েছে।</p></div><div>{[["গণিতের ভিত্তি","জ্যামিতি ও বীজগণিত","৭ দিন"],["বাংলা ব্যাকরণ","ধ্বনি, শব্দতত্ত্ব ও উপসর্গ","৪ দিন"],["আন্তর্জাতিক বিষয়াবলি","দৈনিক ২০ MCQ","৬ দিন"],["পূর্ণাঙ্গ মক","নেগেটিভ মার্কিংসহ","প্রতি শুক্রবার"]].map((x,i)=><article key={x[0]}><i>{i+1}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{x[2]}</em></article>)}</div><button className="gp-primary" onClick={onComplete}>এই পরিকল্পনা সংরক্ষণ করুন →</button></section></main></div></section>
}
