"use client";

import { useState } from "react";

const examOptions = [
  ["BCS", "প্রিলিমিনারি ও লিখিত প্রস্তুতি"],
  ["BANK", "সরকারি ও বিশেষায়িত ব্যাংক"],
  ["NTRCA", "শিক্ষক নিবন্ধন পরীক্ষা"],
  ["PRIMARY", "প্রাথমিক শিক্ষক নিয়োগ"],
];

const prepSteps = ["পরীক্ষা", "ডায়াগনস্টিক", "পরিকল্পনা", "শেখা", "MCQ", "মক পরীক্ষা", "AI ফিডব্যাক", "প্রস্তুতি রিপোর্ট"];

export default function GovernmentPrep({exit}:{exit:()=>void}) {
  const [step,setStep]=useState(0);
  const [exam,setExam]=useState(0);
  const [answer,setAnswer]=useState<number|null>(null);
  const [planDone,setPlanDone]=useState<number[]>([]);
  const [practice,setPractice]=useState<number[]>([]);
  const [mockSubmitted,setMockSubmitted]=useState(false);

  const next=()=>setStep(s=>Math.min(7,s+1));
  const back=()=>step?setStep(s=>s-1):exit();
  const screens=[
    <section className="gp-screen" key="exam"><div className="gp-title"><span>ধাপ ০১ · লক্ষ্য নির্বাচন</span><h1>কোন পরীক্ষার জন্য প্রস্তুতি নিতে চান?</h1><p>একটি পরীক্ষা দিয়ে শুরু করুন। পরে আপনার ড্যাশবোর্ড থেকে অন্য লক্ষ্য যোগ করতে পারবেন।</p></div><div className="gp-exam-grid">{examOptions.map((item,i)=><button key={item[0]} className={exam===i?"selected":""} onClick={()=>setExam(i)}><i>{["▥","৳","◇","✎"][i]}</i><b>{item[0]}</b><small>{item[1]}</small><em>{exam===i?"✓ নির্বাচিত":"নির্বাচন করুন →"}</em></button>)}</div><div className="gp-info"><b>আপনার নির্বাচিত লক্ষ্য</b><span>{examOptions[exam][0]} · {examOptions[exam][1]}</span></div></section>,
    <section className="gp-screen" key="diagnostic"><div className="gp-title"><span>ধাপ ০২ · ডায়াগনস্টিক</span><h1>বর্তমান প্রস্তুতি যাচাই করুন</h1><p>বাংলা, ইংরেজি, গণিত, সাধারণ জ্ঞান ও মানসিক দক্ষতার সংক্ষিপ্ত পরীক্ষা।</p></div><div className="gp-question"><header><b>প্রশ্ন ৮ / ২০</b><span>গণিত · শতকরা</span></header><div className="gp-progress"><i style={{width:"40%"}}/></div><h2>একটি পণ্যের মূল্য ২০% বাড়িয়ে আবার ২০% কমালে মূল্যের মোট পরিবর্তন কত?</h2><div>{["পরিবর্তন হবে না","৪% কমবে","৪% বাড়বে","৮% কমবে"].map((x,i)=><button className={answer===i?"chosen":""} onClick={()=>setAnswer(i)} key={x}><i>{answer===i?"✓":String.fromCharCode(65+i)}</i>{x}</button>)}</div>{answer!==null&&<p className={answer===1?"correct":"incorrect"}>{answer===1?"সঠিক! ধারাবাহিক শতকরা পরিবর্তনে ভিত্তিমূল্য বদলে যায়।":"আবার চেষ্টা করুন। দ্বিতীয় ২০% নতুন মূল্যের ওপর প্রযোজ্য।"}</p>}</div></section>,
    <section className="gp-screen" key="plan"><div className="gp-title"><span>ধাপ ০৩ · ব্যক্তিগত পরিকল্পনা</span><h1>আপনার ১২ সপ্তাহের প্রস্তুতি পরিকল্পনা</h1><p>ডায়াগনস্টিক ফল, পরীক্ষার তারিখ ও প্রতিদিনের সময় অনুযায়ী AI এই পরিকল্পনা তৈরি করেছে।</p></div><div className="gp-plan-head"><div><small>প্রস্তুতি স্কোর</small><b>৬৮%</b></div><div><small>প্রতিদিনের লক্ষ্য</small><b>৯০ মিনিট</b></div><div><small>পরীক্ষা পর্যন্ত</small><b>৮৪ দিন</b></div></div><div className="gp-plan">{[["গণিতের ভিত্তি শক্ত করুন","শতকরা, অনুপাত, লাভ-ক্ষতি · ৭ দিন"],["ইংরেজি ব্যাকরণ অনুশীলন","Parts of speech, tense, correction · ৬ দিন"],["বাংলাদেশ বিষয়াবলি রিভিশন","ইতিহাস, সংবিধান, অর্থনীতি · ৮ দিন"],["সাপ্তাহিক মক পরীক্ষা","প্রতি শুক্রবার · ১০০ MCQ"]].map((x,i)=><button onClick={()=>setPlanDone(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])} className={planDone.includes(i)?"done":""} key={x[0]}><i>{planDone.includes(i)?"✓":i+1}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{planDone.includes(i)?"সম্পন্ন":"শুরু করুন →"}</em></button>)}</div></section>,
    <section className="gp-screen" key="learn"><div className="gp-title"><span>ধাপ ০৪ · AI টিউটর</span><h1>দুর্বল বিষয় শিখুন, নিজের ভাষায়</h1><p>জটিল ধারণা বাংলায় বা ইংরেজিতে বুঝুন এবং সঙ্গে সঙ্গে ছোট অনুশীলন করুন।</p></div><div className="gp-tutor"><aside><b>আজকের পাঠ</b>{["শতকরা পরিবর্তন","অনুপাত ও সমানুপাত","লাভ ও ক্ষতি","সময় ও কাজ"].map((x,i)=><button className={i===0?"active":""} key={x}>{i===0?"▶":"○"} {x}</button>)}</aside><article><small>গণিত · ১২ মিনিট</small><h2>শতকরা পরিবর্তন কীভাবে কাজ করে?</h2><p>শতকরা পরিবর্তন সবসময় বর্তমান ভিত্তিমূল্যের ওপর গণনা করা হয়। তাই ২০% বৃদ্ধি এবং ২০% হ্রাস একে অপরকে বাতিল করে না।</p><div className="gp-example"><b>উদাহরণ</b><span>৳১০০ → ২০% বৃদ্ধি = ৳১২০ → ২০% হ্রাস = ৳৯৬</span><strong>মোট পরিবর্তন: ৪% হ্রাস</strong></div><button className="gp-primary">AI টিউটরকে প্রশ্ন করুন →</button></article></div></section>,
    <section className="gp-screen" key="practice"><div className="gp-title"><span>ধাপ ০৫ · দৈনিক MCQ</span><h1>আজকের ব্যক্তিগত অনুশীলন</h1><p>দুর্বল বিষয় বেশি এবং শক্তিশালী বিষয় কম—আপনার পারফরম্যান্স অনুযায়ী প্রশ্ন বদলাবে।</p></div><div className="gp-daily"><div className="gp-daily-score"><b>{practice.length}/5</b><span>আজ সম্পন্ন</span><div><i style={{width:practice.length*20+"%"}}/></div></div>{["বাংলা ব্যাকরণ · ১০ MCQ","ইংরেজি correction · ১০ MCQ","গণিত: অনুপাত · ১৫ MCQ","বাংলাদেশ বিষয়াবলি · ১০ MCQ","মানসিক দক্ষতা · ৫ MCQ"].map((x,i)=><button onClick={()=>setPractice(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])} className={practice.includes(i)?"done":""} key={x}><i>{practice.includes(i)?"✓":i+1}</i><span><b>{x}</b><small>{["৮ মিনিট","১০ মিনিট","১৫ মিনিট","৯ মিনিট","৬ মিনিট"][i]}</small></span><em>{practice.includes(i)?"সম্পন্ন":"শুরু →"}</em></button>)}</div></section>,
    <section className="gp-screen" key="mock"><div className="gp-title"><span>ধাপ ০৬ · মক পরীক্ষা</span><h1>{examOptions[exam][0]} পূর্ণাঙ্গ মক পরীক্ষা</h1><p>বাস্তব পরীক্ষার মতো সময়সীমা, নেগেটিভ মার্কিং ও বিষয়ভিত্তিক প্রশ্ন।</p></div><div className="gp-mock"><div className="gp-clock"><small>বাকি সময়</small><b>১:৪২:১৮</b></div><div className="gp-mock-meta"><span><b>১০০</b> প্রশ্ন</span><span><b>২০০</b> নম্বর</span><span><b>১২০</b> মিনিট</span><span><b>-০.৫</b> ভুল উত্তরে</span></div><div className="gp-palette">{Array.from({length:20},(_,i)=><i className={i<12?"answered":i===12?"current":""} key={i}>{i+1}</i>)}</div><button className="gp-primary" onClick={()=>setMockSubmitted(true)}>{mockSubmitted?"✓ পরীক্ষা জমা হয়েছে":"মক পরীক্ষা জমা দিন"}</button></div></section>,
    <section className="gp-screen" key="feedback"><div className="gp-title"><span>ধাপ ০৭ · AI ফিডব্যাক</span><h1>কোথায় ভুল হয়েছে এবং কেন</h1><p>প্রতিটি ভুলের ব্যাখ্যা, সময় ব্যবস্থাপনা এবং পরবর্তী অনুশীলনের সুপারিশ।</p></div><div className="gp-feedback"><div className="gp-score-ring"><b>৭৪</b><small>/১০০</small><span>মক স্কোর</span></div><div className="gp-analysis"><h3>AI বিশ্লেষণ</h3><p>আপনি জ্ঞানভিত্তিক প্রশ্নে ভালো করেছেন, কিন্তু গণিতে দীর্ঘ সময় নিয়েছেন এবং শেষ ১২টি প্রশ্ন দ্রুত শেষ করেছেন।</p><div><span>সঠিক উত্তর <b>৭৪</b></span><span>ভুল উত্তর <b>১৮</b></span><span>উত্তরহীন <b>৮</b></span></div></div></div><div className="gp-gaps"><article><small>প্রধান দুর্বলতা</small><h3>ইংরেজি বাক্য সংশোধন</h3><p>Subject–verb agreement এবং modifier অনুশীলন করুন।</p></article><article><small>সময় ব্যবস্থাপনা</small><h3>গণিতে ১২ মিনিট বেশি</h3><p>কঠিন প্রশ্ন চিহ্নিত করে পরে ফেরার কৌশল ব্যবহার করুন।</p></article><article><small>পরবর্তী পদক্ষেপ</small><h3>২টি লক্ষ্যভিত্তিক সেট</h3><p>আগামীকাল ২০টি ইংরেজি ও ১৫টি গণিত প্রশ্ন।</p></article></div></section>,
    <section className="gp-screen" key="readiness"><div className="gp-title"><span>ধাপ ০৮ · প্রস্তুতি রিপোর্ট</span><h1>আপনার পরীক্ষার প্রস্তুতি অবস্থান</h1><p>ডায়াগনস্টিক, দৈনিক অনুশীলন ও মক পরীক্ষার সামগ্রিক বিশ্লেষণ।</p></div><div className="gp-ready"><div className="gp-score-ring large"><b>৭৬%</b><span>প্রস্তুত</span></div><div><small>{examOptions[exam][0]} প্রস্তুতি</small><h2>ভালো অগ্রগতি—আরও ধারাবাহিক অনুশীলন দরকার</h2><p>বর্তমান গতিতে পরিকল্পনা অনুসরণ করলে পরীক্ষার আগে প্রধান দুর্বল বিষয়গুলো সম্পন্ন করা সম্ভব।</p><button className="gp-primary">আমার পরবর্তী ৭ দিনের পরিকল্পনা →</button></div></div><div className="gp-readiness-bars">{[["সিলেবাস কভারেজ",78],["MCQ নির্ভুলতা",74],["সময় ব্যবস্থাপনা",62],["মক পরীক্ষার ধারাবাহিকতা",81]].map(x=><div key={x[0]}><span>{x[0]}<b>{x[1]}%</b></span><i><em style={{width:x[1]+"%"}}/></i></div>)}</div></section>
  ];

  return <main className="gp-portal"><header className="gp-nav"><button className="gp-logo" onClick={exit}><img src="/careerhub-logo.png" alt="Career Hub"/></button><nav><button onClick={exit}>হোম</button><button>ক্যারিয়ার ও চাকরি</button><button className="active">পরীক্ষার প্রস্তুতি</button><button>কাউন্সেলিং</button><button>CV টুলস</button></nav><div><button>English</button><button className="gp-login">লগইন</button></div></header><div className="gp-layout"><aside className="gp-sidebar"><div className="gp-side-title"><small>{examOptions[exam][0]} প্রস্তুতি</small><b>আপনার অগ্রগতি</b><div><i style={{width:(step+1)*12.5+"%"}}/></div><span>৮টি ধাপের মধ্যে {step+1}টি</span></div>{prepSteps.map((x,i)=><button onClick={()=>setStep(i)} className={(step===i?"active ":"")+(i<step?"done":"")} key={x}><i>{i<step?"✓":i+1}</i><span><b>{x}</b><small>{["লক্ষ্য ঠিক করুন","বর্তমান অবস্থা জানুন","পথ তৈরি করুন","AI টিউটরের সঙ্গে","দৈনিক অনুশীলন","পরীক্ষার অভিজ্ঞতা","ভুল বুঝুন","অগ্রগতি জানুন"][i]}</small></span></button>)}<div className="gp-help"><b>বিশেষজ্ঞ সহায়তা</b><p>পরিকল্পনা বুঝতে সমস্যা হলে একজন কাউন্সেলরের সঙ্গে কথা বলুন।</p><button>সেশন বুক করুন →</button></div></aside><div className="gp-workspace"><div className="gp-content">{screens[step]}</div><footer><button onClick={back}>← {step?"পেছনে":"হোম"}</button><button className="gp-primary" onClick={step===7?exit:next}>{step===7?"ড্যাশবোর্ডে ফিরুন ✓":"সংরক্ষণ করে এগিয়ে যান →"}</button></footer></div></div></main>;
}
