"use client";
import { useState } from "react";

const steps = [
  ["Explore","Careers, training & opportunities"],["Join","Create and verify an account"],
  ["Profile","Build your profile and goal"],["Assess","Interests, skills & readiness"],
  ["Report","Readiness and pathways"],["My plan","Personalised next steps"],
  ["Counselling","Get human guidance"],["Prepare","CV, portfolio & interviews"],
  ["Apply","Verified opportunities"],["Progress","Placement and follow-up"],
];
const careers=[["Customer experience","Communication · Service","Entry friendly","☎"],["Digital & IT","Technology · Problem solving","High growth","⌘"],["Banking & finance","Numbers · Business","Professional","▥"],["Development sector","Community · Impact","Purpose led","◉"],["Manufacturing","Operations · Quality","Hands-on","⚙"],["Healthcare support","Care · Organisation","People focused","✚"]];

function Mark(){return <div className="mark"><span>BRAC</span><b>Career<br/>Hub</b></div>}

function Home({start}:{start:(n?:number)=>void}){
 return <main>
  <header className="nav wrap"><Mark/><nav><a href="#explore">Explore</a><a href="#services">Services</a><a href="#journey">How it works</a><a href="#opportunities">Opportunities</a></nav><div className="navActions"><button>বাংলা</button><button onClick={()=>start(1)}>Log in</button><button className="primary small" onClick={()=>start(0)}>Start your journey →</button></div></header>
  <section className="hero"><div className="glow"/><div className="wrap heroGrid">
   <div className="heroCopy"><div className="eyebrow">— YOUR NEXT STEP STARTS HERE</div><h1>Build a career<br/>with <em>direction.</em></h1><p>Explore possibilities, understand your strengths and follow a personalised path—from first question to first day at work.</p><div className="heroButtons"><button className="primary" onClick={()=>start(0)}>Start my career journey →</button><a href="#explore">Explore careers ↘</a></div><div className="trust"><div><i>RA</i><i>NS</i><i>TA</i></div><p><b>Guidance that stays with you</b><br/>Online and at a Career Hub near you</p></div></div>
   <div className="heroVisual"><div className="orbit"/><div className="journeyCard"><div className="cardTop"><span>Your career journey</span><b>20% complete</b></div><h3>Good afternoon, Rafia 👋</h3><p>Here is your recommended next step.</p><div className="nextCard"><span>◎</span><div><small>NEXT STEP</small><b>Discover your career interests</b><em>8-minute assessment</em></div><button onClick={()=>start(3)}>Begin →</button></div><div className="miniStats"><div><b>03</b><small>Careers saved</small></div><div><b>01</b><small>Course active</small></div><div><b>82%</b><small>Profile strength</small></div></div></div><div className="float one">✦ <span><small>NEW MATCH</small><b>Junior Executive</b><em>92% match · Dhaka</em></span></div><div className="float two">✓ <span><b>Counsellor available</b><em>Book a 30-min session</em></span></div></div>
  </div></section>
  <section className="proof"><div className="wrap"><div><b>One connected journey</b><span>From exploration to employment</span></div><div><b>4 service pillars</b><span>Skills, guidance, readiness, linkage</span></div><div><b>Human + digital support</b><span>Self-serve, with people when needed</span></div><div><b>Verified opportunities</b><span>Jobs, internships and apprenticeships</span></div></div></section>
  <section className="section wrap" id="services"><Header kicker="HOW WE HELP" title={<>Everything you need to<br/><em>move forward.</em></>} copy="Career Hub brings fragmented career support into one simple, guided experience designed around your immediate goal."/><div className="services">
   {[["01","↗","Training Hub","Learn practical, employer-relevant skills through flexible courses and guided pathways."],["02","◇","Career Counselling","Turn uncertainty into a clear direction with trained career counsellors."],["03","✓","Job Readiness","Build your CV, practise interviews and become confident for the workplace."],["04","⌁","Opportunity Linkage","Connect with verified jobs, internships, apprenticeships and career events."]].map((s,i)=><article className={i===1?"featured":""} key={s[0]}><small>{s[0]}</small><i>{s[1]}</i><h3>{s[2]}</h3><p>{s[3]}</p><button onClick={()=>start([5,6,7,8][i])}>Explore service <span>→</span></button></article>)}
  </div></section>
  <section className="explore" id="explore"><div className="wrap"><Header light kicker="EXPLORE YOUR OPTIONS" title={<>A future that fits<br/><em>who you are.</em></>} copy="Start with curiosity. Compare career families, see the skills they need and save the ones that feel right."/><div className="careerGrid">{careers.map((c,i)=><button className="career" key={c[0]} onClick={()=>start(0)}><div className={"art art"+i}><b>{c[3]}</b><small>{c[2]}</small></div><div><h3>{c[0]}</h3><p>{c[1]}</p><span>↗</span></div></button>)}</div><button className="all" onClick={()=>start(0)}>Explore all career paths →</button></div></section>
  <section className="section wrap journey" id="journey"><div className="journeyIntro"><span className="kicker">YOUR CAREER JOURNEY</span><h2>One clear path.<br/><em>Ten meaningful steps.</em></h2><p>Your plan adapts as you learn, build skills and connect with opportunities. A counsellor can step in whenever you need support.</p><button className="primary" onClick={()=>start(0)}>See my path →</button></div><div className="timeline">{steps.map((s,i)=><button key={s[0]} onClick={()=>start(i)}><i>{String(i+1).padStart(2,"0")}</i><span><b>{s[0]}</b><small>{s[1]}</small></span><em>→</em></button>)}</div></section>
  <section className="cta" id="opportunities"><div className="wrap"><div><span className="kicker">READY WHEN YOU ARE</span><h2>Your career does not need a perfect plan.<br/>Just a <em>first step.</em></h2></div><button onClick={()=>start(0)}>Start my journey →</button></div></section>
  <footer><div className="wrap footer"><Mark/><p>Skills. Guidance. Opportunity.<br/>All in one place.</p><div><b>Explore</b><a href="#explore">Careers</a><a href="#services">Training</a><a href="#opportunities">Jobs & events</a></div><div><b>Support</b><a href="#journey">How it works</a><button onClick={()=>start(6)}>Book counselling</button><a href="#">Find a centre</a></div><div><b>Connect</b><a href="https://careerhub.brac.net/">Current Career Hub</a><a href="https://www.facebook.com/careerhub.brac">Facebook</a></div></div><div className="wrap copyright">© BRAC Career Hub <span>Concept platform redesign</span></div></footer>
 </main>
}

function Header({kicker,title,copy,light=false}:{kicker:string,title:React.ReactNode,copy:string,light?:boolean}){return <div className={"sectionHead "+(light?"light":"")}><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><p>{copy}</p></div>}

const Content=({step}:{step:number})=>{
 const screens=[
  <><Title n="01" name="EXPLORE" h="What would you like to discover?" p="Browse freely before creating an account. Save anything that interests you."/><div className="search">⌕<input placeholder="Search careers, courses, events or opportunities"/><button>Search</button></div><div className="filters">{["Careers","Training","Events","Centres","Opportunities"].map((x,i)=><button className={i?"":"active"} key={x}>{x}</button>)}</div><div className="portalCards">{careers.slice(0,3).map((c,i)=><article key={c[0]}><div className={"thumb art"+i}>{c[3]}</div><small>{c[2]}</small><h3>{c[0]}</h3><p>{c[1]}</p><button>View pathway →</button></article>)}</div></>,
  <><Title n="02" name="ACCOUNT" h="Create your Career Hub account" p="It takes about two minutes. Your progress will be saved securely."/><div className="formCard"><label>Mobile number</label><div className="phone"><span>+880</span><input defaultValue="17 0000 0000"/></div><button className="primary full">Send verification code</button><div className="or">──────── or continue with email ────────</div><button className="outline full">✉ Continue with email</button><p>By continuing, you agree to the platform terms and privacy notice.</p></div></>,
  <><Title n="03" name="CAREER PROFILE" h="What is your immediate goal?" p="Your answer helps us shape the right journey. You can change it at any time."/><div className="goals">{[["⌕","Find a job now","I want suitable opportunities"],["↗","Build job-ready skills","I need practical training"],["◇","Choose a career direction","I want to understand my options"],["▣","Prepare for applications","I need a CV and interview practice"]].map((g,i)=><button className={i?"":"selected"} key={g[1]}><i>{g[0]}</i><b>{g[1]}</b><small>{g[2]}</small><em>{i?"":"✓"}</em></button>)}</div></>,
  <><Title n="04" name="ASSESSMENT" h="Let’s understand how you work best" p="There are no wrong answers. Choose the response that feels most like you."/><div className="assessment"><div><b>Career interests</b><span>Question 3 of 12</span></div><div className="progress"><i/></div><h2>I enjoy explaining an idea so that other people can understand it.</h2><div className="scale">{["Not like me","A little","Sometimes","Mostly","Very much"].map((x,i)=><button className={i===3?"chosen":""} key={x}><i>{i===3?"✓":i+1}</i><span>{x}</span></button>)}</div></div></>,
  <><Title n="05" name="READINESS REPORT" h="Your Career Readiness Report" p="A practical snapshot of where you are now and what will help you move forward."/><div className="report"><div className="score"><div><b>68</b><small>/100</small></div><strong>Developing</strong><p>You have a strong foundation. Focus on evidence, interview confidence and targeted applications.</p></div><div className="dimensions">{[["Career clarity",78],["Core skills",72],["Job-search readiness",54],["Workplace confidence",66]].map(x=><div key={x[0]}><span>{x[0]}<b>{x[1]}%</b></span><i><em style={{width:x[1]+"%"}}/></i></div>)}</div></div><div className="recommend"><b>Recommended pathway</b><span>Job Preparation Sprint · 4 weeks</span><button>View my plan →</button></div></>,
  <><Title n="06" name="PERSONALISED PLAN" h="Your path to a customer experience role" p="Complete these actions in order. Your plan updates as you make progress."/><div className="plan">{[["done","Complete career profile","10 min"],["current","Customer service essentials","2 hrs"],["","Build a role-specific CV","30 min"],["","Practise a mock interview","20 min"],["","Apply to 3 matched roles","This week"]].map((x,i)=><div className={x[0]} key={x[1]}><i>{x[0]==="done"?"✓":i+1}</i><span><b>{x[1]}</b><small>{x[2]}</small></span>{x[0]==="current"&&<button>Continue →</button>}</div>)}</div></>,
  <><Title n="07" name="COUNSELLING" h="Talk it through with a career counsellor" p="Recommended because your assessment showed competing career interests."/><div className="counselling"><div className="counsellor"><div>SA</div><span><small>RECOMMENDED FOR YOU</small><h3>Samira Ahmed</h3><p>Career counsellor · 6 years experience</p><em>Bangla · English · Online</em></span></div><div className="slots"><b>Select a date</b><div>{["MON|18","TUE|19","WED|20","THU|21"].map((x,i)=><button className={i===1?"chosen":""} key={x}>{x.split("|")[0]}<b>{x.split("|")[1]}</b></button>)}</div><b>Available times</b><div>{["10:00 AM","11:30 AM","3:00 PM"].map((x,i)=><button className={i===1?"chosen":""} key={x}>{x}</button>)}</div><button className="primary full">Book free session →</button></div></div></>,
  <><Title n="08" name="PREPARE" h="Make your application stand out" p="Build evidence for your chosen role, then practise presenting it with confidence."/><div className="tools">{[["▤","CV BUILDER","Customer Experience CV","Tailored to highlight communication, service and problem-solving.","Continue CV →"],["◉","MOCK INTERVIEW","Practise with an AI coach","Answer 6 role-specific questions and receive actionable feedback.","Start practice →"]].map(x=><article key={x[1]}><i>{x[0]}</i><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p><div className="toolbar"><em/></div><b>{x[1]==="CV BUILDER"?"75% complete":"Not attempted"}</b><button>{x[4]}</button></article>)}</div></>,
  <><Title n="09" name="OPPORTUNITIES" h="Verified matches for your goal" p="Ranked by fit with your profile, skills and preferences—not just keywords."/><div className="jobs">{[["92%","Junior Customer Experience Executive","Aarong","Dhaka · Full-time"],["87%","Customer Support Associate","bKash","Dhaka · Full-time"],["81%","Service Centre Apprentice","BRAC Bank","Dhaka · Apprenticeship"]].map((j,i)=><article key={j[1]}><i>{["A","b","B"][i]}</i><div><span>{j[0]} MATCH</span><h3>{j[1]}</h3><b>{j[2]}</b><p>{j[3]} · Entry level</p></div><button>View & apply →</button></article>)}</div></>,
  <><Title n="10" name="PROGRESS" h="Your progress continues after joining" p="Record your outcome so Career Hub can support your transition and growth."/><div className="outcome"><div className="success"><i>✓</i><div><small>CURRENT STATUS</small><h3>Joined a new role</h3><p>Junior Customer Experience Executive · 02 August 2026</p></div><button>Edit</button></div><div className="follow"><h3>Your follow-up journey</h3>{[["done","Joining check-in","Complete"],["current","3-month check-in","02 November 2026"],["","6-month check-in","02 February 2027"]].map((x,i)=><div className={x[0]} key={x[1]}><i>{x[0]==="done"?"✓":i+1}</i><span><b>{x[1]}</b><small>{x[2]}</small></span>{x[0]==="current"&&<button>Add reminder</button>}</div>)}</div></div></>
 ];return screens[step];
}
function Title({n,name,h,p}:{n:string,name:string,h:string,p:string}){return <div className="portalTitle"><span>STEP {n} · {name}</span><h1>{h}</h1><p>{p}</p></div>}

function Portal({initial,exit}:{initial:number,exit:()=>void}){const[step,setStep]=useState(initial);return <main className="portal"><header className="portalNav"><Mark/><div><button>বাংলা</button><button>◌</button><i>RA</i><span><b>Rafia Akter</b><small>My journey</small></span><button onClick={exit}>×</button></div></header><div className="portalLayout"><aside><div className="asideHead"><small>YOUR PROGRESS</small><b>{step+1} of 10 steps</b><div><i style={{width:(step+1)*10+"%"}}/></div></div><nav>{steps.map((s,i)=><button className={(i===step?"active ":"")+(i<step?"done":"")} onClick={()=>setStep(i)} key={s[0]}><i>{i<step?"✓":i+1}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></button>)}</nav><div className="help"><b>Need help?</b><p>Talk to a Career Hub counsellor.</p><button onClick={()=>setStep(6)}>Get support →</button></div></aside><section className="workspace"><div className="workspaceInner"><Content step={step}/></div><footer className="portalFooter"><button onClick={()=>step?setStep(step-1):exit()}>← {step?"Back":"Home"}</button><button className="primary" onClick={()=>step<9?setStep(step+1):exit()}>{step<9?"Save & continue →":"Finish journey ✓"}</button></footer></section></div></main>}

export default function Page(){const[portal,setPortal]=useState<number|null>(null);return portal===null?<Home start={(n=0)=>setPortal(n)}/>:<Portal initial={portal} exit={()=>setPortal(null)}/>}
