"use client";
import { useState } from "react";

const steps = [
  ["অন্বেষণ","ক্যারিয়ার, প্রশিক্ষণ ও সুযোগ"],["অ্যাকাউন্ট","অ্যাকাউন্ট তৈরি ও যাচাই"],
  ["প্রোফাইল","প্রোফাইল ও লক্ষ্য নির্ধারণ"],["মূল্যায়ন","আগ্রহ, দক্ষতা ও প্রস্তুতি"],
  ["রিপোর্ট","প্রস্তুতি ও সম্ভাব্য পথ"],["আমার পরিকল্পনা","ব্যক্তিগত পরবর্তী পদক্ষেপ"],
  ["কাউন্সেলিং","বিশেষজ্ঞের পরামর্শ"],["প্রস্তুতি","সিভি, পোর্টফোলিও ও সাক্ষাৎকার"],
  ["আবেদন","যাচাইকৃত সুযোগ"],["অগ্রগতি","চাকরি ও ফলো-আপ"],
];
const careers=[["কাস্টমার এক্সপেরিয়েন্স","যোগাযোগ · সেবা","নতুনদের জন্য","☎"],["ডিজিটাল ও আইটি","প্রযুক্তি · সমস্যা সমাধান","দ্রুত বিকাশমান","⌘"],["ব্যাংকিং ও ফাইন্যান্স","সংখ্যা · ব্যবসা","পেশাদার","▥"],["উন্নয়ন খাত","কমিউনিটি · প্রভাব","উদ্দেশ্যনির্ভর","◉"],["উৎপাদন খাত","অপারেশন · গুণমান","হাতে-কলমে","⚙"],["স্বাস্থ্যসেবা সহায়তা","সেবা · ব্যবস্থাপনা","মানুষকেন্দ্রিক","✚"]];

function Mark(){return <div className="mark"><img src="/careerhub-logo.png" alt="Career Hub — Powered by BRAC"/></div>}

function Home({start}:{start:(n?:number)=>void}){
 return <main>
  <header className="nav wrap"><Mark/><nav><a href="#explore">ক্যারিয়ার দেখুন</a><a href="#services">সেবাসমূহ</a><a href="#journey">কীভাবে কাজ করে</a><a href="#opportunities">সুযোগসমূহ</a></nav><div className="navActions"><button>English</button><button onClick={()=>start(1)}>লগইন</button><button className="primary small" onClick={()=>start(0)}>যাত্রা শুরু করুন →</button></div></header>
  <section className="hero"><div className="glow"/><div className="wrap heroGrid">
   <div className="heroCopy"><div className="eyebrow">— আপনার পরবর্তী পদক্ষেপ এখান থেকেই</div><h1>সঠিক দিকনির্দেশনায়<br/><em>গড়ুন ক্যারিয়ার।</em></h1><p>সম্ভাবনা অন্বেষণ করুন, নিজের শক্তি বুঝুন এবং প্রথম প্রশ্ন থেকে কর্মজীবনের প্রথম দিন পর্যন্ত একটি ব্যক্তিগত পথ অনুসরণ করুন।</p><div className="heroButtons"><button className="primary" onClick={()=>start(0)}>আমার ক্যারিয়ার যাত্রা শুরু করুন →</button><a href="#explore">ক্যারিয়ার দেখুন ↘</a></div><div className="trust"><div><i>রা</i><i>নি</i><i>তা</i></div><p><b>আপনার পাশে থাকা দিকনির্দেশনা</b><br/>অনলাইনে এবং নিকটস্থ ক্যারিয়ার হাবে</p></div></div>
   <div className="heroVisual"><img className="heroImage" src="/career-journey-hero.png" alt="শিক্ষা থেকে কর্মজীবনে এগিয়ে যাওয়া একজন তরুণী"/></div>
  </div></section>
  <section className="proof"><div className="wrap"><div><b>ব্যক্তিগত AI মূল্যায়ন</b><span>আপনার আগ্রহ, দক্ষতা ও প্রস্তুতি জানুন</span></div><div><b>ব্যক্তিগত কাউন্সেলিং</b><span>বিশেষজ্ঞের সঙ্গে নিজের পথ ঠিক করুন</span></div><div><b>AI ক্যারিয়ার টুল</b><span>সিভি, সাক্ষাৎকার ও ক্যারিয়ার প্রস্তুতি</span></div><div><b>যাচাইকৃত সুযোগ</b><span>চাকরি, ইন্টার্নশিপ ও শিক্ষানবিশি</span></div></div></section>
  <section className="section wrap" id="services"><Header kicker="আমরা যেভাবে সহায়তা করি" title={<>আপনার জন্য ব্যক্তিগত<br/><em>ক্যারিয়ার সহায়তা।</em></>} copy="AI-এর গতি এবং মানুষের অভিজ্ঞতা একসঙ্গে—যাতে আপনি সঠিক সিদ্ধান্ত নিয়ে আত্মবিশ্বাসের সঙ্গে এগোতে পারেন।"/><div className="services">
   {[["০১","◎","ব্যক্তিগত AI ক্যারিয়ার মূল্যায়ন","আপনার আগ্রহ, দক্ষতা ও চাকরির প্রস্তুতি বিশ্লেষণ করে উপযোগী ক্যারিয়ার পথ ও পরবর্তী পদক্ষেপ সুপারিশ করে।"],["০২","◇","ব্যক্তিগত কাউন্সেলিং","AI রিপোর্টের ভিত্তিতে একজন ক্যারিয়ার কাউন্সেলরের সঙ্গে কথা বলুন এবং আপনার বাস্তবতা অনুযায়ী পরিকল্পনা তৈরি করুন।"],["০৩","✦","সিভি ও ক্যারিয়ারের AI টুল","ভূমিকাভিত্তিক সিভি তৈরি, মক সাক্ষাৎকার অনুশীলন এবং আবেদন উন্নত করতে স্মার্ট টুল ব্যবহার করুন।"]].map((s,i)=><article className={i===1?"featured":""} key={s[0]}><small>{s[0]}</small><i>{s[1]}</i><h3>{s[2]}</h3><p>{s[3]}</p><button onClick={()=>start([3,6,7][i])}>শুরু করুন <span>→</span></button></article>)}
  </div></section>
  <section className="explore" id="explore"><div className="wrap"><Header light kicker="আপনার বিকল্পগুলো জানুন" title={<>আপনার সঙ্গে মানানসই<br/><em>একটি ভবিষ্যৎ।</em></>} copy="কৌতূহল দিয়ে শুরু করুন। বিভিন্ন ক্যারিয়ার তুলনা করুন, প্রয়োজনীয় দক্ষতা জানুন এবং পছন্দের পথ সংরক্ষণ করুন।"/><div className="careerGrid">{careers.map((c,i)=><button className="career" key={c[0]} onClick={()=>start(0)}><div className={"art art"+i}><b>{c[3]}</b><small>{c[2]}</small></div><div><h3>{c[0]}</h3><p>{c[1]}</p><span>↗</span></div></button>)}</div><button className="all" onClick={()=>start(0)}>সব ক্যারিয়ার পথ দেখুন →</button></div></section>
  <section className="section wrap journey" id="journey"><div className="journeyIntro"><span className="kicker">আপনার ক্যারিয়ার যাত্রা</span><h2>একটি স্পষ্ট পথ।<br/><em>দশটি অর্থবহ ধাপ।</em></h2><p>আপনি শেখা, দক্ষতা গড়া ও সুযোগের সঙ্গে যুক্ত হওয়ার সঙ্গে সঙ্গে পরিকল্পনাটি বদলাবে। সহায়তা প্রয়োজন হলে কাউন্সেলর পাশে থাকবেন।</p><button className="primary" onClick={()=>start(0)}>আমার পথ দেখুন →</button></div><div className="timeline">{steps.map((s,i)=><button key={s[0]} onClick={()=>start(i)}><i>{String(i+1).padStart(2,"0")}</i><span><b>{s[0]}</b><small>{s[1]}</small></span><em>→</em></button>)}</div></section>
  <section className="cta" id="opportunities"><div className="wrap"><div><span className="kicker">আপনি প্রস্তুত হলেই</span><h2>ক্যারিয়ারের জন্য নিখুঁত পরিকল্পনা নয়,<br/>প্রয়োজন শুধু <em>প্রথম পদক্ষেপ।</em></h2></div><button onClick={()=>start(0)}>যাত্রা শুরু করুন →</button></div></section>
  <footer><div className="wrap footer"><Mark/><p>দক্ষতা। দিকনির্দেশনা। সুযোগ।<br/>সবকিছু এক জায়গায়।</p><div><b>অন্বেষণ</b><a href="#explore">ক্যারিয়ার</a><a href="#services">প্রশিক্ষণ</a><a href="#opportunities">চাকরি ও ইভেন্ট</a></div><div><b>সহায়তা</b><a href="#journey">কীভাবে কাজ করে</a><button onClick={()=>start(6)}>কাউন্সেলিং বুক করুন</button><a href="#">কেন্দ্র খুঁজুন</a></div><div><b>যোগাযোগ</b><a href="https://careerhub.brac.net/">বর্তমান ক্যারিয়ার হাব</a><a href="https://www.facebook.com/careerhub.brac">ফেসবুক</a></div></div><div className="wrap copyright">© BRAC Career Hub <span>প্ল্যাটফর্ম পুনর্নকশার ধারণা</span></div></footer>
 </main>
}

function Header({kicker,title,copy,light=false}:{kicker:string,title:React.ReactNode,copy:string,light?:boolean}){return <div className={"sectionHead "+(light?"light":"")}><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><p>{copy}</p></div>}

const Content=({step}:{step:number})=>{
 const screens=[
  <><Title n="০১" name="অন্বেষণ" h="আপনি কী জানতে চান?" p="অ্যাকাউন্ট তৈরির আগেই স্বাধীনভাবে দেখুন এবং পছন্দের বিষয় সংরক্ষণ করুন।"/><div className="search">⌕<input placeholder="ক্যারিয়ার, কোর্স, ইভেন্ট বা সুযোগ খুঁজুন"/><button>খুঁজুন</button></div><div className="filters">{["ক্যারিয়ার","প্রশিক্ষণ","ইভেন্ট","কেন্দ্র","সুযোগ"].map((x,i)=><button className={i?"":"active"} key={x}>{x}</button>)}</div><div className="portalCards">{careers.slice(0,3).map((c,i)=><article key={c[0]}><div className={"thumb art"+i}>{c[3]}</div><small>{c[2]}</small><h3>{c[0]}</h3><p>{c[1]}</p><button>পথটি দেখুন →</button></article>)}</div></>,
  <><Title n="০২" name="অ্যাকাউন্ট" h="আপনার ক্যারিয়ার হাব অ্যাকাউন্ট তৈরি করুন" p="মাত্র দুই মিনিট সময় লাগবে। আপনার অগ্রগতি নিরাপদে সংরক্ষিত থাকবে।"/><div className="formCard"><label>মোবাইল নম্বর</label><div className="phone"><span>+৮৮০</span><input defaultValue="১৭ ০০০০ ০০০০"/></div><button className="primary full">যাচাইকরণ কোড পাঠান</button><div className="or">──────── অথবা ইমেইল ব্যবহার করুন ────────</div><button className="outline full">✉ ইমেইল দিয়ে এগিয়ে যান</button><p>এগিয়ে যাওয়ার মাধ্যমে আপনি প্ল্যাটফর্মের শর্ত ও গোপনীয়তা নীতিতে সম্মতি দিচ্ছেন।</p></div></>,
  <><Title n="০৩" name="ক্যারিয়ার প্রোফাইল" h="আপনার তাৎক্ষণিক লক্ষ্য কী?" p="আপনার উত্তর অনুযায়ী সঠিক যাত্রাপথ তৈরি হবে। এটি যেকোনো সময় বদলাতে পারবেন।"/><div className="goals">{[["⌕","এখনই চাকরি খুঁজতে চাই","আমার উপযোগী সুযোগ চাই"],["↗","চাকরির দক্ষতা গড়তে চাই","আমার ব্যবহারিক প্রশিক্ষণ দরকার"],["◇","ক্যারিয়ারের দিক বেছে নিতে চাই","আমার বিকল্পগুলো বুঝতে চাই"],["▣","আবেদনের প্রস্তুতি নিতে চাই","সিভি ও সাক্ষাৎকার অনুশীলন দরকার"]].map((g,i)=><button className={i?"":"selected"} key={g[1]}><i>{g[0]}</i><b>{g[1]}</b><small>{g[2]}</small><em>{i?"":"✓"}</em></button>)}</div></>,
  <><Title n="০৪" name="মূল্যায়ন" h="আপনি কীভাবে সবচেয়ে ভালো কাজ করেন তা জানি" p="কোনো উত্তর ভুল নয়। আপনার সঙ্গে সবচেয়ে বেশি মেলে এমন উত্তর বেছে নিন।"/><div className="assessment"><div><b>ক্যারিয়ারের আগ্রহ</b><span>১২টির মধ্যে ৩ নম্বর প্রশ্ন</span></div><div className="progress"><i/></div><h2>আমি কোনো ধারণা এমনভাবে বোঝাতে পছন্দ করি, যাতে অন্যরা সহজে বুঝতে পারে।</h2><div className="scale">{["আমার মতো নয়","কিছুটা","মাঝেমধ্যে","বেশিরভাগ সময়","খুব বেশি"].map((x,i)=><button className={i===3?"chosen":""} key={x}><i>{i===3?"✓":i+1}</i><span>{x}</span></button>)}</div></div></>,
  <><Title n="০৫" name="প্রস্তুতি রিপোর্ট" h="আপনার ক্যারিয়ার প্রস্তুতি রিপোর্ট" p="আপনি এখন কোথায় আছেন এবং সামনে এগোতে কী দরকার—তার ব্যবহারিক চিত্র।"/><div className="report"><div className="score"><div><b>৬৮</b><small>/১০০</small></div><strong>বিকাশমান</strong><p>আপনার ভিত্তি শক্ত। প্রমাণ, সাক্ষাৎকারের আত্মবিশ্বাস এবং লক্ষ্যভিত্তিক আবেদনে মনোযোগ দিন।</p></div><div className="dimensions">{[["ক্যারিয়ারের স্পষ্টতা",78],["মূল দক্ষতা",72],["চাকরি খোঁজার প্রস্তুতি",54],["কর্মক্ষেত্রের আত্মবিশ্বাস",66]].map(x=><div key={x[0]}><span>{x[0]}<b>{x[1]}%</b></span><i><em style={{width:x[1]+"%"}}/></i></div>)}</div></div><div className="recommend"><b>প্রস্তাবিত পথ</b><span>চাকরি প্রস্তুতি স্প্রিন্ট · ৪ সপ্তাহ</span><button>আমার পরিকল্পনা দেখুন →</button></div></>,
  <><Title n="০৬" name="ব্যক্তিগত পরিকল্পনা" h="কাস্টমার এক্সপেরিয়েন্স ভূমিকায় আপনার পথ" p="ক্রম অনুযায়ী কাজগুলো শেষ করুন। অগ্রগতির সঙ্গে পরিকল্পনা হালনাগাদ হবে।"/><div className="plan">{[["done","ক্যারিয়ার প্রোফাইল সম্পন্ন করুন","১০ মিনিট"],["current","গ্রাহকসেবার মৌলিক বিষয়","২ ঘণ্টা"],["","ভূমিকাভিত্তিক সিভি তৈরি করুন","৩০ মিনিট"],["","মক সাক্ষাৎকার অনুশীলন করুন","২০ মিনিট"],["","মিলে যাওয়া ৩টি পদে আবেদন করুন","এই সপ্তাহে"]].map((x,i)=><div className={x[0]} key={x[1]}><i>{x[0]==="done"?"✓":i+1}</i><span><b>{x[1]}</b><small>{x[2]}</small></span>{x[0]==="current"&&<button>চালিয়ে যান →</button>}</div>)}</div></>,
  <><Title n="০৭" name="কাউন্সেলিং" h="ক্যারিয়ার কাউন্সেলরের সঙ্গে কথা বলুন" p="আপনার মূল্যায়নে একাধিক আগ্রহ দেখা গেছে, তাই এই সেশনটি সুপারিশ করা হয়েছে।"/><div className="counselling"><div className="counsellor"><div>সা</div><span><small>আপনার জন্য সুপারিশকৃত</small><h3>সামিরা আহমেদ</h3><p>ক্যারিয়ার কাউন্সেলর · ৬ বছরের অভিজ্ঞতা</p><em>বাংলা · ইংরেজি · অনলাইন</em></span></div><div className="slots"><b>তারিখ নির্বাচন করুন</b><div>{["সোম|১৮","মঙ্গল|১৯","বুধ|২০","বৃহঃ|২১"].map((x,i)=><button className={i===1?"chosen":""} key={x}>{x.split("|")[0]}<b>{x.split("|")[1]}</b></button>)}</div><b>খালি সময়</b><div>{["সকাল ১০:০০","সকাল ১১:৩০","বিকেল ৩:০০"].map((x,i)=><button className={i===1?"chosen":""} key={x}>{x}</button>)}</div><button className="primary full">বিনামূল্যে সেশন বুক করুন →</button></div></div></>,
  <><Title n="০৮" name="প্রস্তুতি" h="আপনার আবেদনকে আলাদা করে তুলুন" p="নির্বাচিত ভূমিকার প্রমাণ তৈরি করুন এবং আত্মবিশ্বাসের সঙ্গে উপস্থাপনের অনুশীলন করুন।"/><div className="tools">{[["▤","সিভি নির্মাতা","কাস্টমার এক্সপেরিয়েন্স সিভি","যোগাযোগ, সেবা ও সমস্যা সমাধানের দক্ষতা তুলে ধরতে তৈরি।","সিভি চালিয়ে যান →"],["◉","মক সাক্ষাৎকার","এআই কোচের সঙ্গে অনুশীলন","ভূমিকাভিত্তিক ৬টি প্রশ্নের উত্তর দিন এবং কার্যকর মতামত পান।","অনুশীলন শুরু করুন →"]].map(x=><article key={x[1]}><i>{x[0]}</i><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p><div className="toolbar"><em/></div><b>{x[1]==="সিভি নির্মাতা"?"৭৫% সম্পন্ন":"এখনও শুরু হয়নি"}</b><button>{x[4]}</button></article>)}</div></>,
  <><Title n="০৯" name="সুযোগসমূহ" h="আপনার লক্ষ্যের সঙ্গে যাচাইকৃত মিল" p="শুধু কীওয়ার্ড নয়—প্রোফাইল, দক্ষতা ও পছন্দ অনুযায়ী সাজানো।"/><div className="jobs">{[["৯২%","জুনিয়র কাস্টমার এক্সপেরিয়েন্স এক্সিকিউটিভ","আড়ং","ঢাকা · পূর্ণকালীন"],["৮৭%","কাস্টমার সাপোর্ট অ্যাসোসিয়েট","বিকাশ","ঢাকা · পূর্ণকালীন"],["৮১%","সার্ভিস সেন্টার শিক্ষানবিশ","ব্র্যাক ব্যাংক","ঢাকা · শিক্ষানবিশি"]].map((j,i)=><article key={j[1]}><i>{["A","b","B"][i]}</i><div><span>{j[0]} মিল</span><h3>{j[1]}</h3><b>{j[2]}</b><p>{j[3]} · প্রারম্ভিক স্তর</p></div><button>দেখুন ও আবেদন করুন →</button></article>)}</div></>,
  <><Title n="১০" name="অগ্রগতি" h="চাকরিতে যোগদানের পরও আপনার যাত্রা চলবে" p="ফলাফল নথিভুক্ত করুন, যাতে ক্যারিয়ার হাব আপনার পরিবর্তন ও বিকাশে সহায়তা করতে পারে।"/><div className="outcome"><div className="success"><i>✓</i><div><small>বর্তমান অবস্থা</small><h3>নতুন পদে যোগ দিয়েছেন</h3><p>জুনিয়র কাস্টমার এক্সপেরিয়েন্স এক্সিকিউটিভ · ০২ আগস্ট ২০২৬</p></div><button>সম্পাদনা</button></div><div className="follow"><h3>আপনার ফলো-আপ যাত্রা</h3>{[["done","যোগদান যাচাই","সম্পন্ন"],["current","৩ মাসের ফলো-আপ","০২ নভেম্বর ২০২৬"],["","৬ মাসের ফলো-আপ","০২ ফেব্রুয়ারি ২০২৭"]].map((x,i)=><div className={x[0]} key={x[1]}><i>{x[0]==="done"?"✓":i+1}</i><span><b>{x[1]}</b><small>{x[2]}</small></span>{x[0]==="current"&&<button>রিমাইন্ডার দিন</button>}</div>)}</div></div></>
 ];return screens[step];
}
function Title({n,name,h,p}:{n:string,name:string,h:string,p:string}){return <div className="portalTitle"><span>ধাপ {n} · {name}</span><h1>{h}</h1><p>{p}</p></div>}

function Portal({initial,exit}:{initial:number,exit:()=>void}){const[step,setStep]=useState(initial);return <main className="portal"><header className="portalNav"><Mark/><div><button>English</button><button>◌</button><i>রা</i><span><b>রাফিয়া আক্তার</b><small>আমার যাত্রা</small></span><button onClick={exit}>×</button></div></header><div className="portalLayout"><aside><div className="asideHead"><small>আপনার অগ্রগতি</small><b>১০টি ধাপের মধ্যে {step+1}টি</b><div><i style={{width:(step+1)*10+"%"}}/></div></div><nav>{steps.map((s,i)=><button className={(i===step?"active ":"")+(i<step?"done":"")} onClick={()=>setStep(i)} key={s[0]}><i>{i<step?"✓":i+1}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></button>)}</nav><div className="help"><b>সহায়তা দরকার?</b><p>ক্যারিয়ার হাব কাউন্সেলরের সঙ্গে কথা বলুন।</p><button onClick={()=>setStep(6)}>সহায়তা নিন →</button></div></aside><section className="workspace"><div className="workspaceInner"><Content step={step}/></div><footer className="portalFooter"><button onClick={()=>step?setStep(step-1):exit()}>← {step?"পেছনে":"হোম"}</button><button className="primary" onClick={()=>step<9?setStep(step+1):exit()}>{step<9?"সংরক্ষণ করে এগিয়ে যান →":"যাত্রা শেষ করুন ✓"}</button></footer></section></div></main>}

export default function Page(){const[portal,setPortal]=useState<number|null>(null);return portal===null?<Home start={(n=0)=>setPortal(n)}/>:<Portal initial={portal} exit={()=>setPortal(null)}/>}
